#!/usr/bin/env python3
"""从原 APK 的 dex 里提取 AndroidX / Material 的 R 类，补进我们构建的 APK。

## 为什么需要

AndroidX 的 `R$string` / `R$id` / `R$layout` 这类资源索引类，
**不随 AAR 发布** —— 它们由 Gradle 的 `generateDebugRFile` 在构建时
根据 R.txt 生成，编译进最终的 dex。

我们的构建复用了原 APK 的 `resources.arsc`，所以资源 ID 与原版一致，
但代码里引用 `androidx.startup.R$string.xxx` 时会找不到类，
运行时报：

    java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/startup/R$string;

## 解决

原 APK 的 dex 里本来就有这些 R 类（原版构建时生成的）。
把它们提取出来，转成 .class 加进我们的编译产物即可。

实现：用 androguard 把原 APK 里所有 `**/R$*.class` 与 `**/R.class`
导出成 Java 源码（只有常量），再编译。

更省事的办法：直接用 dexlib/androguard 把类**原样**提取成 .class 是不可能的
（dex ≠ class）。所以这里生成**等价的 Java 源码**：从 R.txt 或 dex 里的
静态字段值生成。

用法:
    python tools/gen_androidx_r.py          # 生成到 build-manual/gen-androidx/
"""
import os
import re
import struct
import subprocess
import sys
import zipfile

try:
    from loguru import logger
    logger.remove()
except Exception:
    pass

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
PROJ = os.path.dirname(ROOT)
OUT = os.path.join(ROOT, "host-apk", "build-manual", "gen-androidx")

SDK = os.environ.get("ANDROID_HOME") or os.path.join(
    os.environ.get("LOCALAPPDATA", ""), "Android", "Sdk")
AAPT2 = os.path.join(SDK, "build-tools", "34.0.0", "aapt2.exe")

# 取原 APK 的完整资源表，按包名分组
PKG_RE = re.compile(r"^Package name=(\S+) id=([0-9a-f]+)")
TYPE_RE = re.compile(r"^\s+type (\S+) id=([0-9a-f]+)")
RES_RE = re.compile(r"^\s+resource 0x([0-9a-f]{8}) (\S+)/(\S+)")


def find_apk():
    for c in ("Riruriru Mod_1.1.2.apk.1", "Riruriru Mod_1.1.2.apk"):
        p = os.path.join(PROJ, c)
        if os.path.exists(p):
            return p
    return None


def parse_table(apk):
    """aapt2 dump resources -> {pkg: {type: [(name, id)]}}"""
    r = subprocess.run([AAPT2, "dump", "resources", apk],
                       capture_output=True, text=True,
                       encoding="utf-8", errors="replace")
    pkgs = {}
    cur = cur_type = None
    for line in (r.stdout or "").splitlines():
        m = PKG_RE.match(line)
        if m:
            cur = m.group(1)
            pkgs.setdefault(cur, {})
            cur_type = None
            continue
        m = TYPE_RE.match(line)
        if m and cur:
            cur_type = m.group(1)
            pkgs[cur].setdefault(cur_type, [])
            continue
        m = RES_RE.match(line)
        if m and cur and cur_type:
            rid = int(m.group(1), 16)
            name = re.sub(r"[^0-9A-Za-z_]", "_", m.group(3))
            if name and name[0].isdigit():
                name = "_" + name
            pkgs[cur][cur_type].append((name, rid))
    return pkgs


def main():
    apk = find_apk()
    if not apk:
        print("找不到原 APK")
        return 1
    print("从 %s 读取资源表 ..." % os.path.basename(apk))
    pkgs = parse_table(apk)
    print("包数: %d" % len(pkgs))

    # 只处理 AndroidX / Material / 其它库包（自有包 com.Riruriru.Sx 已单独处理）
    skip = {"com.Riruriru.Sx", "android"}
    nfile = 0
    nfield = 0
    for pkg, types in pkgs.items():
        if pkg in skip:
            continue
        # 只处理 androidx / com.google.android.material 之类
        if not (pkg.startswith("androidx.") or
                pkg.startswith("com.google.android.")):
            continue
        pkgdir = os.path.join(OUT, pkg.replace(".", os.sep))
        os.makedirs(pkgdir, exist_ok=True)

        with open(os.path.join(pkgdir, "R.java"), "w", encoding="utf-8") as f:
            f.write("/* AUTO-GENERATED by tools/gen_androidx_r.py\n"
                    " * AndroidX/Material 的资源索引类，从原 APK 的资源表还原。\n"
                    " * 不手改。\n */\n")
            f.write("package %s;\n\n" % pkg)
            f.write("public final class R {\n")
            for t in sorted(types):
                f.write("    public static final class %s {\n" % t)
                for name, rid in sorted(types[t]):
                    f.write("        public static final int %s = 0x%08x;\n"
                            % (name, rid))
                    nfield += 1
                f.write("    }\n")
            f.write("}\n")
        nfile += 1

    print("生成 %d 个 AndroidX R 类，%d 个字段" % (nfile, nfield))
    print("输出:", OUT)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
