#!/usr/bin/env python3
"""从原 APK 的资源表生成 R.java。

## 为什么需要它

我们的构建复用原 APK 的 `resources.arsc`（因为 AndroidX 有 2000+ 资源，
aapt2 link 的参数会超过 Windows 命令行上限）。但源码里引用了 `R.layout.xxx`
这类符号，需要一份**与那份 arsc 匹配的 R.java**。

从 `aapt2 dump resources` 的输出解析出全部资源 ID 与名字，生成 R.java。
这样生成出来的常量值与 arsc 里的完全一致。

用法:
    python tools/gen_rjava.py                       # 从原 APK 生成
    python tools/gen_rjava.py --apk <path> -o out
"""
import os
import re
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
PROJ = os.path.dirname(ROOT)

SDK = os.environ.get("ANDROID_HOME") or os.path.join(
    os.environ.get("LOCALAPPDATA", ""), "Android", "Sdk")
AAPT2 = os.path.join(SDK, "build-tools", "34.0.0", "aapt2.exe")

OUT = os.path.join(ROOT, "host-apk", "build-manual", "gen")


def find_apk():
    for c in ("Riruriru Mod_1.1.2.apk.1", "Riruriru Mod_1.1.2.apk"):
        p = os.path.join(PROJ, c)
        if os.path.exists(p):
            return p
    return None


# aapt2 dump resources 的输出格式：
#   Package name=com.Riruriru.Sx id=7f
#     type anim id=01 entryCount=44
#       resource 0x7f010000 anim/abc_fade_in
#          ...
#   Package name=android id=01
#     ...
PKG_RE = re.compile(r"^Package name=(\S+) id=([0-9a-f]+)")
TYPE_RE = re.compile(r"^\s+type (\S+) id=([0-9a-f]+)")
RES_RE = re.compile(r"^\s+resource 0x([0-9a-f]{8}) (\S+)/(\S+)")


def main():
    apk = None
    if "--apk" in sys.argv:
        apk = sys.argv[sys.argv.index("--apk") + 1]
    else:
        apk = find_apk()
    outdir = OUT
    if "-o" in sys.argv:
        outdir = sys.argv[sys.argv.index("-o") + 1]

    if not apk or not os.path.exists(apk):
        print("找不到原 APK")
        return 1

    print("从 %s 读取资源表 ..." % os.path.basename(apk))
    r = subprocess.run([AAPT2, "dump", "resources", apk],
                       capture_output=True, text=True,
                       encoding="utf-8", errors="replace")
    text = (r.stdout or "") + (r.stderr or "")
    if not text.strip():
        print("aapt2 dump 无输出")
        return 1

    # 只关心自有包；同时收集 android 包（备用）
    pkgs = {}       # pkgname -> {type: [(name, id)]}
    cur_pkg = None
    cur_type = None
    for line in text.splitlines():
        m = PKG_RE.match(line)
        if m:
            cur_pkg = m.group(1)
            pkgs.setdefault(cur_pkg, {})
            cur_type = None
            continue
        m = TYPE_RE.match(line)
        if m and cur_pkg:
            cur_type = m.group(1)
            pkgs[cur_pkg].setdefault(cur_type, [])
            continue
        m = RES_RE.match(line)
        if m and cur_pkg and cur_type:
            rid, tp, name = m.group(1), m.group(2), m.group(3)
            # 名字里可能有 .9 之类，转成合法 Java 标识符
            safe = re.sub(r"[^0-9A-Za-z_]", "_", name)
            if safe and safe[0].isdigit():
                safe = "_" + safe
            pkgs[cur_pkg][cur_type].append((safe, int(rid, 16), name))

    if not pkgs:
        print("没解析到任何包")
        return 1

    print("解析到包: %s" % ", ".join(pkgs))
    total = sum(len(v) for t in pkgs.values() for v in t.values())
    print("资源条目: %d" % total)

    # 生成 R.java
    os.makedirs(outdir, exist_ok=True)
    nfile = 0
    for pkg, types in pkgs.items():
        if pkg == "android":
            continue                    # android 的 R 用系统自带的
        pkgpath = os.path.join(outdir, pkg.replace(".", os.sep))
        os.makedirs(pkgpath, exist_ok=True)
        # 主 R
        with open(os.path.join(pkgpath, "R.java"), "w", encoding="utf-8") as f:
            f.write("/* AUTO-GENERATED by tools/gen_rjava.py\n"
                    " * 从 %s 的资源表生成，与复用的 resources.arsc 匹配。\n"
                    " * 不要手改。\n */\n" % os.path.basename(apk))
            f.write("package %s;\n\n" % pkg)
            f.write("public final class R {\n")
            for t in sorted(types):
                # 类型名保持小写（R.layout / R.id / R.drawable）——
                # 源码里就是这么引用的，首字母大写会找不到
                cls = t
                f.write("    public static final class %s {\n" % cls)
                for name, rid, _orig in sorted(types[t]):
                    f.write("        public static final int %s = 0x%08x;\n"
                            % (name, rid))
                f.write("    }\n")
            f.write("}\n")
        nfile += 1
        # 注意：Java 源码里写的是 R.layout.xxx（嵌套类），
        # 所以只生成一个 R.java 带嵌套类即可，
        # 生成 R$Layout.java 这种独立文件反而编译不过。

    print("生成 %d 个 R 文件 -> %s" % (nfile, outdir))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
